export const store = {
  positions: [
    {
      id: 1,
      category: 'meat',
      image: 'img/cards/1.png',
      name: 'Бургер классический',
      composition: 'Говяжья котлета, листья салата, помидоры, моцарелла, лук, огурцы маринованные, томатный соус',
      price: 199,
      amount: 1,
    },
    {
      id: 2,
      category: 'meat',
      image: 'img/cards/2.png',
      name: 'Бургер Фирменный',
      composition: `Говяжья котлета, листья салата, помидоры, моцарелла,
      огурцы маринованные, французский соус, картофельные чипсы`,
      price: 279,
      amount: 1,
    },
    {
      id: 3,
      category: 'meat',
      image: 'img/cards/3.png',
      name: 'Бургер “Цыпленок”',
      composition: `Куриное филе, листья салата, помидоры, бекон, огурцы маринованные, соус тар-тар`,
      price: 259,
      amount: 1,
    },
    {
      id: 4,
      category: 'spicy',
      image: 'img/cards/4.png',
      name: 'Чили-бургер',
      composition: `Говяжья котлета, листья салата, помидоры, сыр Дор-блю,
      огурцы свежие, чили соус, горчица, красный лук, бекон`,
      price: 249,
      amount: 1,
    },
    {
      id: 5,
      category: 'spicy',
      image: 'img/cards/5.png',
      name: 'Бургер “Двойной удар”',
      composition: `Двойная говяжья котлета, листья салата, помидоры, моцарелла,
      сыр чеддер огурцы свежие, бекон, красный лук, горчичный соус`,
      price: 349,
      amount: 1,
    },
    {
      id: 6,
      category: 'vegan',
      image: 'img/cards/6.png',
      name: 'Веган-бургер',
      composition: `Овощная котлета, листья салата, помидоры, сыр чеддер, огурцы свежие, французский соус, лук`,
      price: 179,
      amount: 1,
    },
  ],
  filters: [
    {
      category: 'all',
      name: 'все',
    },
    {
      category: 'spicy',
      name: 'острые',
    },
    {
      category: 'meat',
      name: 'мясные',
    },
    {
      category: 'vegan',
      name: 'веган',
    },
  ],
};
